usage: hidl-gen [-p <root path>] -o <output path> -L <language> (-r <interface root>)+ fqname+
 -h: Prints this menu.
 -L <language>: The following options are available:
    check           : Parses the interface to see if valid but doesn't write any files.
    c++             : (internal) (deprecated) Generates C++ interface files for talking to HIDL interfaces.
    c++-headers     : (internal) Generates C++ headers for interface files for talking to HIDL interfaces.
    c++-sources     : (internal) Generates C++ sources for interface files for talking to HIDL interfaces.
    export-header   : Generates a header file from @export enumerations to help maintain legacy code.
    c++-impl        : Generates boilerplate implementation of a hidl interface in C++ (for convenience).
    java            : (internal) Generates Java library for talking to HIDL interfaces in Java.
    java-constants  : (internal) Like export-header but for Java (always created by -Lmakefile if @export exists).
    vts             : (internal) Generates vts proto files for use in vtsd.
    makefile        : (internal) Generates makefiles for -Ljava and -Ljava-constants.
    androidbp       : (internal) Generates Soong bp files for -Lc++-headers and -Lc++-sources.
    androidbp-impl  : Generates boilerplate bp files for implementation created with -Lc++-impl.
    hash            : Prints hashes of interface in `current.txt` format to standard out.
 -o <output path>: Location to output files.
 -p <root path>: Android build root, defaults to $ANDROID_BUILD_TOP or pwd.
 -r <package:path root>: E.g., android.hardware:hardware/interfaces.



//	下表列出了软件包前缀和位置：
//	软件包前缀		位置
//	android.hardware.*	hardware/interfaces/*
//	android.frameworks.*	frameworks/hardware/interfaces/*  
//	android.system.*	system/hardware/interfaces/*
//	android.hidl.*		system/libhidl/transport/*

通过目下的shell脚本更新库文件,下面以system/hardware/interfaces/update-makefiles.sh例：

#!/bin/bash
source $ANDROID_BUILD_TOP/system/tools/hidl/update-makefiles-helper.sh
do_makefiles_update "android.system:system/hardware/interfaces" "android.hidl:system/libhidl/transport"




//由于上面脚本可知需要配置环境变量ANDROID_BUILD_TOP
export ANDROID_BUILD_TOP=[Android源码路径]


再次展开system/tools/hidl/update-makefiles-helper.sh 中的 do_makefiles_update 函数如下：


//获取包名
function package_root_to_package() {
  echo $1 | cut -f1 -d:
}

//获取路径
function package_root_to_root() {
  echo $1 | cut -f2 -d:
}

//例如：android.system:system/hardware/interfaces
通过package_root_to_package()得到android.system
通过package_root_to_root()得到system/hardware/interfaces




##
# Makes sure the appropriate directories are visible.
# Usage: check_dirs root_or_cwd [package:root ...]
function check_dirs() {
  local root_or_cwd=$1
  shift 1

  for package_root in "$@"; do
      dir=$(package_root_to_root $package_root)
      if [ ! -d $root_or_cwd$dir ] ; then
        echo "Where is $dir?";
        return 1;
      fi
  done
}


##
# Helps manage the package root of a HAL directory.
# Should be called from the android root directory.
#
# Usage: do_makefiles_update [package:root ...]
# Where the first package root is the current one.
#

function do_makefiles_update() {
  local root_or_cwd=${ANDROID_BUILD_TOP%%/}${ANDROID_BUILD_TOP:+/}

  

  local current_package=$(package_root_to_package $1)
  local current_dir=$root_or_cwd$(package_root_to_root $1)

  echo "Updating makefiles for $current_package in $current_dir."

  check_dirs "$root_or_cwd" $@ || return 1

  local packages=$(get_packages $current_dir $current_package) || return 1
  local root_arguments=$(get_root_arguments $@) || return 1

  for p in $packages; do
    echo "Updating $p";
    hidl-gen -Lmakefile $root_arguments $p;
    rc=$?; if [[ $rc != 0 ]]; then return $rc; fi
    hidl-gen -Landroidbp $root_arguments $p;
    rc=$?; if [[ $rc != 0 ]]; then return $rc; fi
  done

  local android_dirs=$(get_bp_dirs $current_dir) || return 1

  echo "Updating Android.bp files."

  for bp_dir in $android_dirs; do
    bp="$bp_dir/Android.bp"
    # locations of Android.bp files in specific subdirectory of frameworks/hardware/interfaces
    android_bps=$(find $bp_dir                   \
                  -name "Android.bp"             \
                  ! -path $bp_dir/Android.bp     \
                  -printf "%h\n"                 \
                  | sort)

    echo "// This is an autogenerated file, do not edit." > "$bp";
    echo "subdirs = [" >> "$bp";
    for a in $android_bps; do
      echo "    \"${a#$bp_dir/}\"," >> "$bp";
    done
    echo "]" >> "$bp";
  done
}


//需要配置hidl-gen环境，最简单方式：
$cd out/host/linux-x86/lib64; 
$sudo cp hidl-gen /usr/bin
$sudo cp libbase.so liblog.so libhidl-gen*.so libcrypto-host.so libssl-host.so /usr/lib

//编译结果：
Updating makefiles for android.system in /work/workcodes/android-O/system/hardware/interfaces.
Updating android.system.net.netd@1.0
Updating android.system.wifi.keystore@1.0
Updating Android.bp files.


//通过hidl-gen处理的hal文件，都会再out/soong/.intermediates/目录下生成对应文件：
以system/hardware/interfaces为例：
生成文件路径：out/soong/.intermediates/system/hardware/interfaces

out/soong/.intermediates/system/hardware/interfaces/net/netd/1.0$ ll
total 24
drwxrwxr-x 6 xqli xqli 4096  8月 21 17:25 ./
drwxrwxr-x 3 xqli xqli 4096  7月 31 10:53 ../
drwxrwxr-x 3 xqli xqli 4096  7月 31 10:54 android.system.net.netd@1.0/
drwxrwxr-x 3 xqli xqli 4096  7月 31 10:53 android.system.net.netd@1.0_genc++/
drwxrwxr-x 3 xqli xqli 4096  7月 31 10:53 android.system.net.netd@1.0_genc++_headers/








	



//工程路径	system/tools/hidl





